# defining the name of the workflow 
name: CI/CD Pipeline

# specifying this workflow will get triggered if we push anything to the main branch
on:
  push:
    branches:
       - main

# adding environment variables
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: market_basket_analysis
  CONTAINER_NAME: market_basket_analysis
  
  

# defining the jobs
jobs:
  # defining Continous integration which tested our application when any push happends
  Continous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements_dev.txt
      
      - name: Run tests with pytest
        run: pytest test.py
  
  # defining Continous delivery which builds and pushes docker image to AWS ECR
  Continous-Delivery:
    needs: Continous-Integration
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      # sanity check
      - name: Print AWS Secrets
        run: |
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@b8c74de753fbcb4868bf2011fb2e15826ce973af
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ env.AWS_REGION }}
      
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a
        with:
          registry: ${{ steps.login-ecr.outputs.registry }}
          region:  ${{env.AWS_REGION}}
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        
      - name: Build, tag and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image = $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

  # defining Continous deployment which pulls docker image from AWS ECR and pushed it to the EC2 instance
  Continous-Deployment:
    needs: Continous-Delivery
    runs-on: self-hosted
    environment: production
    steps:
      - name: Deploy docker image from ECR to EC2 instance
        id: deploy-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
       
        run: |
             whoami
             aws ecr get-login-password --region us-east-1 | docker login --ubuntu AWS --password-stdin 851725554615.dkr.ecr.us-east-1.amazonaws.com
             docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG;
             docker run -d -p 5000:5000 $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG;
             docker system prune -f

    